### ISSUE TITLE
Available for 64bit laptop please?

### ISSUE THREAD

**Issue by julien-garrigue** [jebeld17/Store-Ports_Thunderbird#1]
Hello,
Could you pleas make this app available for 64bits devices?

Thank you

**Comment by jebeld17** [comment]
Hi Julien,

Unfortunately, the Store Ports Thunderbird port will no longer be visible in the Microsoft Store, upon request from Mozilla.
Not to worry, as Mozilla may have a surprise for you in the near future. ;-)
